version: '3.9'

services:

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - 6379:6379
    networks:
      - network
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: funwell
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

volumes:
  pgdata:
    driver: local

networks:
  network:
    driver: bridge
