version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: file_system
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: 'Admin@123'        
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network

volumes:
  pgdata:
    driver: local

networks:
  network:
    driver: bridge
