// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"core/config"
	"core/internal/entrypoint/http/server"
	"core/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(configPath string) (*server.Application, error) {
	configConfig, err := config.LoadAndParseConfig(configPath)
	if err != nil {
		return nil, err
	}
	loggerLogger := logger.NewApiLogger(configConfig)
	application := server.NewApplication(configConfig, loggerLogger)
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(config.LoadAndParseConfig, logger.NewApiLogger, server.NewApplication)
